#!/bin/bash

echo "-------------------"
echo "BASH FILE ORGANIZER "
echo "-------------------"

read -p "Enter directory to organize : " DIR

if [ ! -d "$DIR" ]; then
echo "Error : Directory does not exist"
exit 1
fi

mkdir -p "$DIR/Documents"
mkdir -p "$DIR/Images"
mkdir -p "$DIR/Videos"
mkdir -p "$DIR/Music"
mkdir -p "$DIR/Archive"
mkdir -p "$DIR/Others"

for FILE in "$DIR"/*; do

if [ -f "FILE" ]; then
EXT="${FILE##*.}"

case "$EXT" in

pdf|doc|docx|txt|odt)
mv "$FILE" "$DIR/Documents/"
;;
jpg|jpeg|png|gif|webp)
mv "$FILE" "$DIR/Images/"
;;
mp4|mkv|avi|mov)
mv "$FILE" "$DIR/Videos/"
;;
mp4|wav|flac)
mv "$FILE" "$DIR/Music/"
;;
zip|tar|gz|rar|7z)
mv "$FILE" "$DIR/Archives/"
;;
*)
mv "$FILE" "$DIR/Others/"
;;

esac

fi

done

echo ""
echo "File oraganized successfully"
